/**
 * COLOSSUS exercise catalog — Cruise Block (Block 1).
 *
 * Hand-authored rather than imported, because the metadata that matters here —
 * ladder edges, breath cues, corrective value, joint load — doesn't exist in
 * any public dataset. `catalog/scripts/build-catalog.mjs` pulls the
 * public-domain free-exercise-db to *expand* this library later with imagery
 * and long-tail movements; it can't replace the authored fields.
 *
 * Two things shape every entry:
 *
 *   Entry rungs sit low. At ~290 lb a full push-up and a pull-up are goals,
 *   not warmups. Ladders that start where you actually are turn a demoralising
 *   gap into a countable number of rungs.
 *
 *   Corrective value is a first-class score. Anti-extension, offset carries,
 *   and breath-driven repositioning directly oppose an anterior pelvic tilt,
 *   a right-side shift, and rolled-forward shoulders.
 *
 * NOTE ON VIDEOS: `videoSearch` holds a precise search query rather than a
 * hardcoded video id. Inventing YouTube ids would produce dead or wrong links,
 * which for technique instruction is worse than no link at all. Verified
 * per-exercise embeds are a follow-up pass.
 */

import type { Exercise } from '../src/engine/types';

type Draft = Omit<Exercise, 'images' | 'secondaryMuscles' | 'instructions'> &
  Partial<Pick<Exercise, 'images' | 'secondaryMuscles' | 'instructions'>> & {
    videoSearch?: string;
  };

function ex(d: Draft): Exercise & { videoSearch?: string } {
  return {
    images: [],
    secondaryMuscles: [],
    instructions: [],
    ...d,
  };
}

export const CATALOG: (Exercise & { videoSearch?: string })[] = [
  /* ---------------------------------------------------------------- *
   * BRIDGE — the corrective centrepiece
   *
   * The 90/90 hip lift is where breath work and posture stop being two
   * separate goals. A full exhale drops the ribcage, which lets the pelvis
   * rotate out of anterior tilt; the position is the drill.
   * ---------------------------------------------------------------- */
  ex({
    id: 'hip-lift-90-90',
    name: '90/90 Hip Lift',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['bridge'],
    equipment: ['mat', 'wall'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.2,
    correctiveFit: 1.0,
    jointLoad: [],
    tempo: 'slow',
    breathCue: 'Exhale fully through the mouth. Feel the ribs drop before you lift.',
    instructions: [
      'Lie on your back, feet flat on a wall, hips and knees at 90 degrees.',
      'Exhale fully through pursed lips until your lower back flattens to the floor.',
      'Keeping that flat back, push through your heels to lift your tailbone an inch.',
      'Hold, breathe quietly through your nose for 4 breaths, then lower.',
    ],
    videoSearch: '90/90 hip lift with balloon PRI tutorial',
    videoUrl: 'https://www.youtube.com/watch?v=DVDBBYeGLsg',
  }),
  ex({
    id: 'glute-bridge',
    name: 'Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'lowerBack'],
    patterns: ['bridge'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.75,
    jointLoad: ['lowBack'],
    progressionOf: 'hip-lift-90-90',
    breathCue: 'Exhale as you lift. Ribs stay down — do not arch to get higher.',
    instructions: [
      'Lie on your back, knees bent, feet flat and hip-width.',
      'Exhale, tuck the pelvis slightly, then drive through your heels.',
      'Stop when your hips are in line with your knees and shoulders.',
      'Lower under control.',
    ],
    videoSearch: 'glute bridge proper form posterior pelvic tilt',
    videoUrl: 'https://www.youtube.com/watch?v=brgT1Qq4Tk0',
  }),
  ex({
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['bridge'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.5,
    correctiveFit: 0.9,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'glute-bridge',
    breathCue: 'Exhale up. Keep both hip bones level — do not let one side hike.',
    instructions: [
      'Set up as a glute bridge, then extend one leg straight.',
      'Drive through the planted heel, keeping the pelvis level.',
      'Lower without letting the free-side hip drop.',
    ],
    videoSearch: 'single leg glute bridge form level hips',
    videoUrl: 'https://www.youtube.com/watch?v=VUl8R0kn6v4',
  }),
  ex({
    id: 'hip-thrust-db',
    name: 'Dumbbell Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    patterns: ['bridge'],
    equipment: ['bench', 'dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.5,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Exhale at the top. Chin tucked, ribs down.',
    instructions: [
      'Sit on the floor with your upper back against a bench, dumbbell across the hips.',
      'Exhale, tuck the pelvis, and drive the hips up until the torso is level.',
      'Pause one second at the top, then lower.',
    ],
    videoSearch: 'dumbbell hip thrust form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * ANTI-EXTENSION — the direct opponent of anterior pelvic tilt
   * ---------------------------------------------------------------- */
  ex({
    id: 'dead-bug',
    name: 'Dead Bug',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['antiExtension'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 1.0,
    jointLoad: [],
    breathCue: 'Long exhale as the limbs travel. The low back never leaves the floor.',
    instructions: [
      'Lie on your back, arms straight up, knees over hips at 90 degrees.',
      'Press your low back into the floor and hold it there.',
      'Exhale slowly while lowering one arm and the opposite leg.',
      'Return, and switch sides. Stop the range where the back starts to lift.',
    ],
    videoSearch: 'dead bug exercise form low back flat',
    videoUrl: 'https://www.youtube.com/watch?v=bxn9FBrt4-A',
  }),
  ex({
    id: 'dead-bug-band',
    name: 'Banded Dead Bug',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lats', 'lowerBack'],
    patterns: ['antiExtension'],
    equipment: ['mat', 'band'],
    loadType: 'band',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.35,
    correctiveFit: 0.95,
    jointLoad: [],
    progressionOf: 'dead-bug',
    breathCue: 'Pull the band down as you exhale — lats and abs together.',
    instructions: [
      'Anchor a band overhead and hold it with straight arms.',
      'Press the band toward your hips to switch on the lats.',
      'Keeping that tension, lower one leg at a time on a long exhale.',
    ],
    videoSearch: 'banded dead bug lat tension core exercise',
    videoUrl: 'https://www.youtube.com/watch?v=6oiD9Yv0CMQ',
  }),
  ex({
    id: 'plank',
    name: 'Front Plank',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes'],
    patterns: ['antiExtension'],
    equipment: ['mat'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.7,
    jointLoad: ['shoulder', 'lowBack'],
    progressionOf: 'dead-bug-band',
    breathCue: 'Breathe. If you cannot talk, the position is too hard, not too good.',
    instructions: [
      'Forearms under shoulders, feet hip-width.',
      'Tuck the pelvis so the low back is flat, and squeeze the glutes.',
      'Hold only as long as that position survives.',
    ],
    videoSearch: 'front plank form posterior pelvic tilt glutes',
  }),

  /* ---------------------------------------------------------------- *
   * ANTI-ROTATION
   * ---------------------------------------------------------------- */
  ex({
    id: 'pallof-press-band',
    name: 'Pallof Press',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes'],
    patterns: ['antiRotation'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.35,
    correctiveFit: 0.95,
    jointLoad: [],
    breathCue: 'Exhale as you press out. Resist the twist — nothing should rotate.',
    instructions: [
      'Anchor a band at chest height and stand side-on, hands at your sternum.',
      'Step out until the band is taut.',
      'Press your hands straight forward and resist the pull toward the anchor.',
      'Return under control.',
    ],
    videoSearch: 'pallof press anti rotation core form',
    videoUrl: 'https://www.youtube.com/watch?v=dBAmQ9bx3JA',
  }),
  ex({
    id: 'pallof-press-half-kneeling',
    name: 'Half-Kneeling Pallof Press',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['glutes', 'shoulders'],
    patterns: ['antiRotation'],
    equipment: ['band', 'mat'],
    loadType: 'band',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.4,
    correctiveFit: 1.0,
    jointLoad: [],
    progressionOf: 'pallof-press-band',
    breathCue: 'Exhale, ribs down, back glute switched on. No arching to press.',
    instructions: [
      'Half-kneel side-on to the anchor, down knee under the hip.',
      'Squeeze the down-side glute and tuck the pelvis.',
      'Press out and resist rotation without letting the ribs flare.',
    ],
    videoSearch: 'half kneeling pallof press form ribs down',
    videoUrl: 'https://www.youtube.com/watch?v=O3LtfPsiRy8',
  }),

  /* ---------------------------------------------------------------- *
   * ROTATION
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-chop-low-high',
    name: 'Low-to-High Band Chop',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes', 'upperBack'],
    patterns: ['rotation'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.4,
    correctiveFit: 0.8,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale through the turn. Rotate from the ribcage, not the low back.',
    instructions: [
      'Anchor a band low and stand side-on.',
      'Pull from the low hip diagonally up and across.',
      'Let the back foot pivot; keep the pelvis stacked over the down leg.',
    ],
    videoSearch: 'low to high band chop rotation exercise form',
  }),
  ex({
    id: 'open-book',
    name: 'Open Book Rotation',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['abs'],
    patterns: ['rotation'],
    equipment: ['mat'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.15,
    correctiveFit: 0.9,
    jointLoad: [],
    breathCue: 'Inhale to open, long exhale at end range.',
    instructions: [
      'Lie on your side, knees stacked at 90 degrees, arms straight in front.',
      'Keeping the knees down, sweep the top arm open across your body.',
      'Follow the hand with your eyes and exhale at the end of the range.',
    ],
    videoSearch: 'open book thoracic rotation stretch form',
    videoUrl: 'https://www.youtube.com/watch?v=peeW19ofFUg',
  }),

  /* ---------------------------------------------------------------- *
   * CARRY — the lateral-shift exercise
   *
   * A suitcase carry is the most direct loaded answer to bearing weight on
   * one side: an offset load forces the opposite lateral core to hold you
   * upright, and it is immediately obvious which side struggles.
   * ---------------------------------------------------------------- */
  ex({
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    primaryMuscles: ['abs', 'forearms'],
    secondaryMuscles: ['upperBack', 'glutes', 'shoulders'],
    patterns: ['carry'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'novice',
    unilateral: true,
    goalFit: 0.7,
    correctiveFit: 1.0,
    jointLoad: ['lowBack', 'shoulder'],
    breathCue: 'Breathe normally. Stay tall — do not lean away from the weight.',
    instructions: [
      'Hold one dumbbell at your side, shoulders level.',
      'Walk slowly, resisting the pull to the loaded side.',
      'Count reps as paces. Match both sides.',
    ],
    videoSearch: 'suitcase carry form anti lateral flexion',
  }),
  ex({
    id: 'farmer-carry',
    name: 'Farmer Carry',
    primaryMuscles: ['forearms', 'upperBack'],
    secondaryMuscles: ['abs', 'shoulders', 'quads'],
    patterns: ['carry'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'lowBack'],
    breathCue: 'Ribs down, chest tall, breathe steady.',
    instructions: [
      'Hold a dumbbell in each hand at your sides.',
      'Stand tall, pull the shoulders back and down, and walk.',
      'Count reps as paces.',
    ],
    videoSearch: 'farmer carry form grip posture',
  }),

  /* ---------------------------------------------------------------- *
   * SQUAT — entry rung is a chair
   * ---------------------------------------------------------------- */
  ex({
    id: 'box-squat',
    name: 'Box Squat (Sit-to-Stand)',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['squat'],
    equipment: ['chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.5,
    jointLoad: ['knee', 'hip'],
    breathCue: 'Inhale down, exhale on the way up.',
    instructions: [
      'Stand in front of a chair, feet shoulder-width.',
      'Push the hips back and sit under control — do not drop.',
      'Stand fully, squeezing the glutes at the top.',
    ],
    videoSearch: 'box squat to chair form beginner',
  }),
  ex({
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'adductors'],
    patterns: ['squat'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.5,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'box-squat',
    breathCue: 'Inhale down, exhale up. Ribs stacked over the pelvis.',
    instructions: [
      'Feet shoulder-width, toes slightly out.',
      'Sit down and back, keeping the whole foot on the floor.',
      'Descend to the depth you can hold without the low back rounding.',
    ],
    videoSearch: 'bodyweight squat form tutorial',
  }),
  ex({
    id: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upperBack', 'adductors'],
    patterns: ['squat'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.7,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'bodyweight-squat',
    tempo: '3-1-1-0',
    breathCue: 'Big breath at the top, hold it down, exhale on the way up.',
    instructions: [
      'Hold a dumbbell vertically against your chest.',
      'Squat between your knees, elbows tracking inside the thighs.',
      'The front load helps keep the chest up — let it.',
    ],
    videoSearch: 'goblet squat form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * LUNGE — all unilateral, all asymmetry-exposing
   * ---------------------------------------------------------------- */
  ex({
    id: 'split-squat-supported',
    name: 'Supported Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    patterns: ['lunge'],
    equipment: ['chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.5,
    correctiveFit: 0.9,
    jointLoad: ['knee', 'hip'],
    breathCue: 'Exhale up. Back-side glute stays switched on throughout.',
    instructions: [
      'Stagger your stance, one hand on a chair for balance.',
      'Drop the back knee straight down.',
      'Push through the front heel to stand. Keep the pelvis square.',
    ],
    videoSearch: 'supported split squat form beginner',
  }),
  ex({
    id: 'split-squat',
    name: 'Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    patterns: ['lunge'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.6,
    correctiveFit: 0.95,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'split-squat-supported',
    breathCue: 'Exhale up. Notice which side wobbles — that is the information.',
    instructions: [
      'Stagger your stance without support.',
      'Lower the back knee straight down under control.',
      'Drive through the front heel, keeping the torso upright.',
    ],
    videoSearch: 'split squat form tutorial',
  }),
  ex({
    id: 'reverse-lunge-db',
    name: 'Dumbbell Reverse Lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'adductors'],
    patterns: ['lunge'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.8,
    correctiveFit: 0.85,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'split-squat',
    breathCue: 'Exhale as you stand. Stay tall through the step back.',
    instructions: [
      'Hold dumbbells at your sides.',
      'Step back and lower the trailing knee toward the floor.',
      'Push through the front heel to return.',
    ],
    videoSearch: 'dumbbell reverse lunge form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * HINGE
   * ---------------------------------------------------------------- */
  ex({
    id: 'hip-hinge-dowel',
    name: 'Hip Hinge Pattern',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['hinge'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.8,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Inhale as you hinge back, exhale as you stand.',
    instructions: [
      'Hold a broomstick along your spine, touching head, mid-back, and tailbone.',
      'Push the hips straight back, letting the knees soften.',
      'Keep all three contact points as you hinge, then stand.',
    ],
    videoSearch: 'hip hinge dowel drill three points of contact',
    videoUrl: 'https://www.youtube.com/watch?v=45DQiwq4oKk',
  }),
  ex({
    id: 'rdl-db',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack', 'upperBack', 'forearms'],
    patterns: ['hinge'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.9,
    correctiveFit: 0.7,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'hip-hinge-dowel',
    tempo: '3-0-1-0',
    breathCue: 'Breath in at the top, hold on the way down, exhale standing up.',
    instructions: [
      'Hold dumbbells in front of your thighs, knees softly bent.',
      'Push the hips back, letting the weights track down your legs.',
      'Stop when the hamstrings tighten or the back starts to round.',
      'Drive the hips forward to stand.',
    ],
    videoSearch: 'dumbbell romanian deadlift form tutorial',
  }),
  ex({
    id: 'single-leg-rdl-supported',
    name: 'Supported Single-Leg RDL',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack', 'abs'],
    patterns: ['hinge'],
    equipment: ['dumbbell', 'chair'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.7,
    correctiveFit: 1.0,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'rdl-db',
    breathCue: 'Exhale standing up. Keep both hip bones pointing at the floor.',
    instructions: [
      'Hold a chair with one hand, dumbbell in the other.',
      'Hinge over the standing leg, letting the free leg travel behind you.',
      'Do not let the free-side hip rotate open.',
    ],
    videoSearch: 'single leg romanian deadlift form hips square',
  }),

  /* ---------------------------------------------------------------- *
   * HORIZONTAL PUSH — the ladder starts at a wall
   * ---------------------------------------------------------------- */
  ex({
    id: 'wall-pushup',
    name: 'Wall Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['wall'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    breathCue: 'Inhale in, exhale pressing away.',
    instructions: [
      'Hands on a wall at chest height, step your feet back.',
      'Lower your chest to the wall with the body in one line.',
      'Press away, spreading the shoulder blades at the top.',
    ],
    videoSearch: 'wall push up proper form beginner',
  }),
  ex({
    id: 'incline-pushup',
    name: 'Incline Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bench'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.45,
    correctiveFit: 0.45,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'wall-pushup',
    breathCue: 'Exhale pressing up. Ribs down — no sagging through the middle.',
    instructions: [
      'Hands on a bench, body in a straight line from head to heels.',
      'Lower the chest to the bench with elbows at about 45 degrees.',
      'Press up and spread the shoulder blades.',
    ],
    videoSearch: 'incline push up form tutorial',
  }),
  ex({
    id: 'knee-pushup',
    name: 'Knee Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.45,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'incline-pushup',
    breathCue: 'Exhale pressing up. Squeeze the glutes to stop the hips sagging.',
    instructions: [
      'Knees on a mat, hands under the shoulders.',
      'Keep a straight line from knees to head.',
      'Lower the chest, then press up.',
    ],
    videoSearch: 'knee push up correct form',
  }),
  ex({
    id: 'pushup',
    name: 'Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.5,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'knee-pushup',
    breathCue: 'Exhale pressing up. Whole body moves as one plank.',
    instructions: [
      'Hands under the shoulders, feet hip-width, body in one line.',
      'Lower until the chest is a fist off the floor.',
      'Press up without letting the hips lead or lag.',
    ],
    videoSearch: 'push up perfect form tutorial',
  }),
  ex({
    id: 'floor-press-db',
    name: 'Dumbbell Floor Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    patterns: ['horizontalPush'],
    equipment: ['dumbbell', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Inhale down, exhale press. Low back stays flat on the floor.',
    instructions: [
      'Lie on your back on a mat, knees bent, dumbbells at chest height.',
      'Press up until the arms are straight.',
      'Lower until the triceps touch the floor, pause, repeat.',
    ],
    videoSearch: 'dumbbell floor press form tutorial',
    videoUrl: 'https://www.youtube.com/watch?v=qHCI9rK7HqM',
  }),

  /* ---------------------------------------------------------------- *
   * VERTICAL PUSH
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-overhead-press',
    name: 'Band Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upperBack', 'abs'],
    patterns: ['verticalPush'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing up. Ribs down — press with the shoulder, not the back.',
    instructions: [
      'Stand on a band, handles at shoulder height.',
      'Press straight overhead without leaning back.',
      'Lower under control.',
    ],
    videoSearch: 'band overhead press form ribs down',
  }),
  ex({
    id: 'overhead-press-db-seated',
    name: 'Seated Dumbbell Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upperBack'],
    patterns: ['verticalPush'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.5,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing up. Back stays flat against the bench.',
    instructions: [
      'Sit upright with back support, dumbbells at shoulder height.',
      'Press overhead until the arms are straight.',
      'Lower to ear height under control.',
    ],
    videoSearch: 'seated dumbbell shoulder press form',
  }),
  ex({
    id: 'half-kneeling-press-db',
    name: 'Half-Kneeling Single-Arm Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['abs', 'triceps', 'glutes'],
    patterns: ['verticalPush'],
    equipment: ['dumbbell', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.75,
    correctiveFit: 0.95,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing. Back glute on, ribs down, no arching.',
    instructions: [
      'Half-kneel with the down knee under the hip, dumbbell in the opposite hand.',
      'Squeeze the down-side glute and tuck the pelvis.',
      'Press overhead without letting the ribs flare or the torso lean.',
    ],
    videoSearch: 'half kneeling single arm dumbbell press form',
    videoUrl: 'https://www.youtube.com/watch?v=d3CRIDSCOhw',
  }),

  /* ---------------------------------------------------------------- *
   * HORIZONTAL PULL — the highest-value pattern here
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-row',
    name: 'Seated Band Row',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['lats', 'biceps', 'forearms'],
    patterns: ['horizontalPull'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.9,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Lead with the shoulder blades, not the hands.',
    instructions: [
      'Sit with legs extended, band around the feet.',
      'Pull the handles to your ribs, squeezing the shoulder blades together.',
      'Return slowly, letting the blades travel forward.',
    ],
    videoSearch: 'seated band row form scapular retraction',
  }),
  ex({
    id: 'bent-row-db',
    name: 'Dumbbell Bent-Over Row',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'lowerBack'],
    patterns: ['horizontalPull'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.95,
    correctiveFit: 0.85,
    jointLoad: ['lowBack', 'shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Chest stays proud, low back neutral.',
    instructions: [
      'Hinge to about 45 degrees, dumbbells hanging.',
      'Row to the ribs, driving the elbows back and squeezing the blades.',
      'Lower under control.',
    ],
    videoSearch: 'dumbbell bent over row form tutorial',
    videoUrl: 'https://www.youtube.com/watch?v=knB5Q4FN4ck',
  }),
  ex({
    id: 'single-arm-row-db',
    name: 'Single-Arm Dumbbell Row',
    primaryMuscles: ['lats', 'upperBack'],
    secondaryMuscles: ['biceps', 'forearms', 'abs'],
    patterns: ['horizontalPull'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.9,
    correctiveFit: 1.0,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Do not let the torso rotate to help.',
    instructions: [
      'One hand and knee on a bench, other foot planted.',
      'Row the dumbbell to your hip, elbow close.',
      'Lower fully and let the shoulder blade reach forward at the bottom.',
    ],
    videoSearch: 'single arm dumbbell row form no rotation',
  }),
  ex({
    id: 'suspension-row',
    name: 'Suspension Row',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['lats', 'biceps', 'abs'],
    patterns: ['horizontalPull'],
    equipment: ['suspension'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.95,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'band-row',
    breathCue: 'Exhale pulling. Body stays one straight line, ribs down.',
    instructions: [
      'Hold the straps and walk your feet forward to set the angle.',
      'Pull your chest to your hands, squeezing the shoulder blades.',
      'The more upright you stand, the easier it is — use that to scale.',
    ],
    videoSearch: 'TRX suspension row form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * VERTICAL PULL — a pull-up is a goal, not a starting point
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-lat-pulldown',
    name: 'Band Lat Pulldown',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps'],
    patterns: ['verticalPull'],
    equipment: ['band', 'pullupBar'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.8,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling down. Start the pull from the armpit.',
    instructions: [
      'Anchor a band over the pull-up bar and kneel underneath.',
      'Pull the band down to your chest, elbows driving to the ribs.',
      'Return slowly and let the shoulder blades rise at the top.',
    ],
    videoSearch: 'band lat pulldown kneeling form',
  }),
  ex({
    id: 'suspension-assisted-pullup',
    name: 'Suspension-Assisted Pull-Up',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['suspension'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.75,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'band-lat-pulldown',
    breathCue: 'Exhale pulling up. Let the legs help exactly as much as needed.',
    instructions: [
      'Set the straps so the handles are at chest height, feet in front.',
      'Pull yourself up, driving the elbows down and back.',
      'Use the legs to assist, taking away help as you get stronger.',
    ],
    videoSearch: 'TRX assisted pull up progression',
  }),
  ex({
    id: 'negative-pullup',
    name: 'Pull-Up Negative',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['pullupBar', 'chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.7,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'suspension-assisted-pullup',
    tempo: '5-0-0-0',
    breathCue: 'Breathe steadily through the descent. Control beats speed.',
    instructions: [
      'Step up so your chin starts above the bar.',
      'Lower yourself as slowly as you can — aim for five seconds.',
      'Step back up to reset. Never drop off the bar.',
    ],
    videoSearch: 'pull up negatives progression tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * NECK — wrestler build and forward-head posture, same work
   * ---------------------------------------------------------------- */
  ex({
    id: 'neck-isometric',
    name: 'Neck Isometrics',
    primaryMuscles: ['neck'],
    secondaryMuscles: [],
    patterns: ['neck'],
    equipment: ['bodyweight'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.8,
    jointLoad: ['neck'],
    breathCue: 'Breathe normally throughout. Never hold your breath here.',
    instructions: [
      'Place a palm on your forehead and press your head into it gently.',
      'Build to about half effort over three seconds and hold.',
      'Repeat on the back and each side. Nothing should move.',
    ],
    videoSearch: 'neck isometric exercise safe form',
  }),
  ex({
    id: 'chin-tuck',
    name: 'Chin Tuck',
    primaryMuscles: ['neck'],
    secondaryMuscles: ['upperBack'],
    patterns: ['neck'],
    equipment: ['bodyweight'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 1.0,
    jointLoad: ['neck'],
    breathCue: 'Exhale as you tuck. Slow and small.',
    instructions: [
      'Sit or stand tall, eyes level.',
      'Draw the chin straight back, making a double chin.',
      'Hold three seconds and release. Small range, no tilting.',
    ],
    videoSearch: 'chin tuck exercise forward head posture',
  }),

  /* ---------------------------------------------------------------- *
   * PHYSIQUE EXPANSION
   *
   * Everything below exists for one reason: the original 39 were heavily
   * corrective and nearly bare of real hypertrophy volume — no barbell, no
   * EZ bar, no cable work, almost no direct arm/delt/calf isolation. A
   * physique program needs the volume that actually builds the look. Every
   * entry here is gated to the gym that actually has the equipment for it —
   * barbell/EZ bar/band/suspension/ab roller are home-only, cable/leg
   * press/kettlebell/medicine ball/battle ropes/bench are apartment-only,
   * per `config/gyms.ts` — so the selector never proposes a cable fly in a
   * living room or a barbell row in an apartment gym you don't have a bar in.
   *
   * Two ladders that were advertised in this file's own header comment but
   * never actually built are completed here: the push-up chain now reaches
   * feet-elevated -> deficit -> archer -> one-arm as documented, and the
   * pull-up chain finally contains an actual pull-up (it previously ended at
   * "negative pull-up," which was the whole bug).
   * ---------------------------------------------------------------- */

  /* ---- Barbell (home) ---- */
  //
  // No barbell bench press: this equipment model never puts a barbell and a
  // bench in the same gym (home has the bar, apartment has the bench), so
  // that entry would be permanently unreachable dead weight. Barbell Floor
  // Press below fills the same horizontalPush/chest role at home.
  ex({
    id: 'barbell-row',
    name: 'Barbell Row',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps', 'shoulders'],
    patterns: ['horizontalPull'],
    equipment: ['barbell'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.9,
    correctiveFit: 0.5,
    jointLoad: ['lowBack', 'shoulder'],
    breathCue: 'Exhale pulling the bar to the ribs. Ribs down, no swinging.',
    instructions: [
      'Hinge to about 45°, flat back, bar hanging at arm’s length.',
      'Pull the bar to the lower ribs, elbows driving back.',
      'Lower under control without losing the hinge.',
    ],
    videoSearch: 'barbell row form tutorial',
  }),
  ex({
    id: 'barbell-rdl',
    name: 'Barbell Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['hinge'],
    equipment: ['barbell'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.4,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Inhale as the bar lowers, exhale standing tall.',
    instructions: [
      'Bar at arm’s length, soft knees, flat back.',
      'Push the hips back, sliding the bar down the thighs.',
      'Stop when the hamstrings are fully loaded, then drive the hips forward.',
    ],
    videoSearch: 'barbell romanian deadlift form tutorial',
  }),
  ex({
    id: 'barbell-floor-press',
    name: 'Barbell Floor Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    patterns: ['horizontalPush'],
    equipment: ['barbell', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.3,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Inhale down, exhale press. Upper arms stop dead on the floor.',
    instructions: [
      'Lie on the floor, bar at arm’s length over the chest.',
      'Lower until the triceps rest on the floor, pause.',
      'Press back up without arching off the floor.',
    ],
    videoSearch: 'barbell floor press form tutorial',
  }),
  ex({
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'abs'],
    patterns: ['verticalPush'],
    equipment: ['barbell'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.9,
    correctiveFit: 0.3,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Brace and exhale driving up. Ribs stay down, don’t lean back.',
    instructions: [
      'Bar at the collarbone, grip just past shoulder width.',
      'Brace the abs and press straight up, tucking the head through at the top.',
      'Lower under control back to the collarbone.',
    ],
    videoSearch: 'barbell overhead press strict form tutorial',
  }),
  ex({
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['bridge'],
    equipment: ['barbell', 'chair'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.55,
    jointLoad: ['hip', 'lowBack'],
    progressionOf: 'hip-thrust-db',
    breathCue: 'Exhale hard at the top, squeezing the glutes, not the low back.',
    instructions: [
      'Upper back braced against a sturdy chair or couch edge, bar across the hips, feet flat.',
      'Drive through the heels, exhaling to full hip extension.',
      'Squeeze at the top, then lower under control.',
    ],
    videoSearch: 'barbell hip thrust form tutorial',
  }),

  /* ---- EZ bar (home) ---- */
  ex({
    id: 'ez-bar-curl',
    name: 'EZ Bar Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    patterns: ['elbowFlexion'],
    equipment: ['ezBar'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow', 'wrist'],
    breathCue: 'Exhale curling up. Elbows stay pinned at your sides.',
    instructions: [
      'Stand tall, EZ bar at arm’s length, elbows tucked.',
      'Curl the bar up without swinging the torso.',
      'Lower all the way under control.',
    ],
    videoSearch: 'EZ bar curl form tutorial',
  }),
  ex({
    id: 'ez-bar-skullcrusher',
    name: 'EZ Bar Floor Skullcrusher',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    patterns: ['elbowExtension'],
    equipment: ['ezBar'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow'],
    breathCue: 'Inhale lowering to the forehead, exhale pressing out.',
    instructions: [
      'Lying on the floor, bar over the chest, upper arms vertical.',
      'Bend only at the elbow, lowering the bar toward the forehead.',
      'Extend back up without letting the upper arms drift.',
    ],
    videoSearch: 'EZ bar skullcrusher form tutorial',
    videoUrl: 'https://www.youtube.com/watch?v=D47mYdoKllE',
  }),
  ex({
    id: 'ez-bar-upright-row',
    name: 'EZ Bar Upright Row',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['upperBack'],
    patterns: ['verticalPull'],
    equipment: ['ezBar'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.65,
    correctiveFit: 0.2,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling up. Stop at chest height, no higher.',
    instructions: [
      'Bar at arm’s length in front of the thighs.',
      'Pull straight up along the body, elbows leading and staying above the wrists.',
      'Lower under control.',
    ],
    videoSearch: 'EZ bar upright row form tutorial shoulder friendly',
  }),
  ex({
    id: 'ez-bar-preacher-curl',
    name: 'EZ Bar Preacher Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    patterns: ['elbowFlexion'],
    equipment: ['ezBar', 'chair'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow'],
    progressionOf: 'ez-bar-curl',
    breathCue: 'Exhale curling up. Never let the elbows leave the pad.',
    instructions: [
      'Chest against the back of a sturdy chair, arms resting on top as the pad.',
      'Curl the bar up without lifting the elbows off the chair back.',
      'Lower all the way to a full stretch under control.',
    ],
    videoSearch: 'EZ bar preacher curl form tutorial',
  }),

  /* ---- Cable (apartment) ---- */
  ex({
    id: 'cable-fly',
    name: 'Cable Fly',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders'],
    patterns: ['horizontalPush'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.2,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale bringing the hands together, feeling the stretch on the way back.',
    instructions: [
      'Cables at chest height, slight bend in the elbows.',
      'Sweep the hands together in front of the chest.',
      'Return slowly until you feel a stretch across the chest, not the shoulders.',
    ],
    videoSearch: 'cable fly form tutorial',
  }),
  ex({
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    primaryMuscles: ['upperBack', 'shoulders'],
    secondaryMuscles: [],
    patterns: ['horizontalPull'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.95,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale pulling to the face, squeezing the shoulder blades together.',
    instructions: [
      'Rope at head height, arms extended.',
      'Pull toward your face, splitting the rope apart, elbows high.',
      'The direct fix for rolled-forward shoulders — feel it between the blades.',
    ],
    videoSearch: 'cable face pull form tutorial rounded shoulders',
  }),
  ex({
    id: 'cable-triceps-pushdown',
    name: 'Cable Triceps Pushdown',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    patterns: ['elbowExtension'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow'],
    breathCue: 'Exhale pressing down. Elbows stay glued to your sides.',
    instructions: [
      'Elbows tucked at your sides, forearms parallel to the floor.',
      'Press the bar or rope down until the arms are straight.',
      'Return under control without letting the elbows flare.',
    ],
    videoSearch: 'cable triceps pushdown form tutorial',
  }),
  ex({
    id: 'cable-lat-pulldown',
    name: 'Cable Lat Pulldown',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps'],
    patterns: ['verticalPull'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling down, driving the elbows to the ribs.',
    instructions: [
      'Grip just past shoulder width, sit tall under the bar.',
      'Pull the bar to the upper chest, leading with the elbows.',
      'Let it rise back under control without leaning back to cheat it.',
    ],
    videoSearch: 'cable lat pulldown form tutorial',
  }),
  ex({
    id: 'cable-seated-row',
    name: 'Cable Seated Row',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps'],
    patterns: ['horizontalPull'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.5,
    jointLoad: ['lowBack', 'shoulder'],
    breathCue: 'Exhale pulling to the stomach, squeezing the shoulder blades.',
    instructions: [
      'Sit tall, knees soft, handle at arm’s length.',
      'Pull to the stomach without leaning back to help.',
      'Return until the shoulder blades protract, then repeat.',
    ],
    videoSearch: 'cable seated row form tutorial',
  }),
  ex({
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    patterns: ['shoulderAbduction'],
    equipment: ['cable'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.75,
    correctiveFit: 0.3,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale raising to shoulder height, no higher.',
    instructions: [
      'Cable at the low pulley, standing sideways to the stack.',
      'Raise the arm out to shoulder height, leading with the elbow.',
      'Lower under control. Constant tension the whole set.',
    ],
    videoSearch: 'cable lateral raise form tutorial',
  }),
  ex({
    id: 'cable-crunch',
    name: 'Cable Crunch',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    patterns: ['coreFlexion'],
    equipment: ['cable', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.2,
    jointLoad: ['lowBack'],
    breathCue: 'Exhale hard curling down. The crunch comes from the ribs, not the hips.',
    instructions: [
      'Kneel below a high pulley, rope behind the head.',
      'Curl the ribs down toward the hips, rounding the spine.',
      'Return only to the start position, keeping tension on.',
    ],
    videoSearch: 'cable crunch form tutorial',
  }),

  /* ---- Leg press (apartment) ---- */
  ex({
    id: 'leg-press',
    name: 'Leg Press',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    patterns: ['squat'],
    equipment: ['legPress'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.15,
    jointLoad: ['knee', 'hip'],
    breathCue: 'Inhale lowering, exhale pressing away.',
    instructions: [
      'Feet shoulder-width on the platform, low back flat on the pad.',
      'Lower until the knees reach about 90°.',
      'Press through the whole foot, without locking the knees out hard.',
    ],
    videoSearch: 'leg press form tutorial knee tracking',
  }),

  /* ---- Kettlebell (apartment) ---- */
  ex({
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lowerBack', 'shoulders'],
    patterns: ['hinge'],
    equipment: ['kettlebell'],
    loadType: 'external',
    impact: 'low',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.35,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Sharp exhale at the top of every rep, driven by the hips, not the arms.',
    instructions: [
      'Hike the bell back between your legs like a football snap.',
      'Snap the hips forward hard, letting the bell float to chest height.',
      'The arms are just along for the ride — power comes from the hips.',
    ],
    videoSearch: 'kettlebell swing form tutorial hip hinge',
  }),
  ex({
    id: 'kettlebell-single-arm-row',
    name: 'Kettlebell Single-Arm Row',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps'],
    patterns: ['horizontalPull'],
    equipment: ['kettlebell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.75,
    correctiveFit: 0.7,
    jointLoad: ['shoulder', 'lowBack'],
    breathCue: 'Exhale pulling. Watch the gap between sides — that’s the point of this one.',
    instructions: [
      'One knee and hand on the bench, flat back, bell hanging straight down.',
      'Pull the bell to the hip, elbow tracking close to the body.',
      'Lower fully under control, then switch sides.',
    ],
    videoSearch: 'kettlebell single arm row form tutorial',
  }),

  /* ---- Medicine ball (apartment) ---- */
  ex({
    id: 'medicine-ball-slam',
    name: 'Medicine Ball Slam',
    primaryMuscles: ['abs', 'shoulders'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['hinge'],
    equipment: ['medicineBall'],
    loadType: 'external',
    impact: 'low',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.2,
    jointLoad: ['lowBack', 'shoulder'],
    breathCue: 'Sharp exhale on the slam. Let it go, don’t chase it down.',
    instructions: [
      'Raise the ball overhead, reaching tall.',
      'Slam it into the floor as hard as you can, folding at the hips.',
      'Pick it up and reset — this one is about intent, not a slow tempo.',
    ],
    videoSearch: 'medicine ball slam form tutorial',
  }),
  ex({
    id: 'medicine-ball-rotational-throw',
    name: 'Medicine Ball Rotational Throw',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders'],
    patterns: ['rotation'],
    equipment: ['medicineBall', 'wall'],
    loadType: 'external',
    impact: 'low',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.5,
    correctiveFit: 0.5,
    jointLoad: ['lowBack'],
    breathCue: 'Exhale sharply on the throw, rotating from the hips.',
    instructions: [
      'Stand sideways to a wall, ball held at the hip.',
      'Rotate through the hips and torso, releasing the ball into the wall.',
      'Catch the rebound and reset. Do both sides.',
    ],
    videoSearch: 'medicine ball rotational throw form tutorial',
  }),

  /* ---- Battle ropes (apartment) ---- */
  ex({
    id: 'battle-rope-waves',
    name: 'Battle Rope Waves',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['forearms', 'abs'],
    patterns: ['carry'],
    equipment: ['battleRopes'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.1,
    jointLoad: ['shoulder'],
    breathCue: 'Steady breathing through the whole interval — don’t hold it.',
    instructions: [
      'Athletic stance, one rope end in each hand.',
      'Whip the ropes in alternating waves, driven from the shoulders.',
      'Keep the core braced the whole interval.',
    ],
    videoSearch: 'battle ropes waves form tutorial',
  }),

  /* ---- Ab roller (home) ---- */
  ex({
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lowerBack', 'shoulders'],
    patterns: ['antiExtension'],
    equipment: ['abRoller', 'mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.8,
    jointLoad: ['lowBack', 'shoulder', 'wrist'],
    progressionOf: 'plank',
    breathCue: 'Exhale rolling out, stopping the instant the low back wants to sag.',
    instructions: [
      'Kneeling, hands on the wheel under the shoulders.',
      'Roll out only as far as you can keep the low back flat.',
      'Pull back to start using the abs, not the hips.',
    ],
    videoSearch: 'ab wheel rollout form tutorial',
  }),

  /* ---- Dumbbell isolation (home + apartment) ---- */
  ex({
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    patterns: ['shoulderAbduction'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.2,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale raising to shoulder height. Lead with the elbows, not the hands.',
    instructions: [
      'Dumbbells at your sides, slight bend in the elbows.',
      'Raise both arms out to shoulder height.',
      'Lower slowly — the negative is where this one is won.',
    ],
    videoSearch: 'dumbbell lateral raise form tutorial',
    videoUrl: 'https://www.youtube.com/watch?v=ssAo_xwFt5c',
  }),
  ex({
    id: 'dumbbell-rear-delt-fly',
    name: 'Dumbbell Rear Delt Fly',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['upperBack'],
    patterns: ['horizontalPull'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.9,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale raising out to the sides, squeezing the shoulder blades.',
    instructions: [
      'Hinge forward at the hips, dumbbells hanging straight down.',
      'Raise both arms out to the sides, leading with the elbows.',
      'Squeeze the shoulder blades together at the top, then lower slowly.',
    ],
    videoSearch: 'dumbbell rear delt fly form tutorial',
  }),
  ex({
    id: 'dumbbell-bicep-curl',
    name: 'Dumbbell Bicep Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    patterns: ['elbowFlexion'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow'],
    breathCue: 'Exhale curling up, elbows pinned to your sides the whole rep.',
    instructions: [
      'Dumbbells at your sides, palms facing forward.',
      'Curl without swinging the torso or drifting the elbows.',
      'Lower all the way under control.',
    ],
    videoSearch: 'dumbbell bicep curl form tutorial',
  }),
  ex({
    id: 'dumbbell-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    patterns: ['elbowFlexion'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.65,
    correctiveFit: 0.1,
    jointLoad: ['elbow', 'wrist'],
    breathCue: 'Exhale curling up. Thumbs stay pointed at the ceiling the whole rep.',
    instructions: [
      'Dumbbells at your sides, palms facing each other.',
      'Curl straight up keeping the neutral grip throughout.',
      'Lower under control.',
    ],
    videoSearch: 'dumbbell hammer curl form tutorial',
  }),
  ex({
    id: 'dumbbell-skullcrusher',
    name: 'Dumbbell Skullcrusher',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    patterns: ['elbowExtension'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.1,
    jointLoad: ['elbow'],
    breathCue: 'Inhale lowering to the forehead, exhale pressing out.',
    instructions: [
      'Lying on a bench, dumbbells over the chest, upper arms vertical.',
      'Bend only at the elbow, lowering toward the forehead.',
      'Press back up without letting the upper arms drift back.',
    ],
    videoSearch: 'dumbbell skullcrusher form tutorial',
  }),
  ex({
    id: 'dumbbell-triceps-kickback',
    name: 'Dumbbell Triceps Kickback',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    patterns: ['elbowExtension'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.6,
    correctiveFit: 0.5,
    jointLoad: ['elbow'],
    breathCue: 'Exhale extending back. Upper arm stays still — only the forearm moves.',
    instructions: [
      'One knee and hand on the bench, upper arm parallel to the floor.',
      'Extend the forearm straight back without moving the upper arm.',
      'Lower under control, then switch sides.',
    ],
    videoSearch: 'dumbbell triceps kickback form tutorial',
  }),

  /* ---- Calves (home + apartment) ---- */
  ex({
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    patterns: ['calfRaise'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.1,
    jointLoad: ['ankle'],
    breathCue: 'Exhale rising onto the toes, pausing at the top.',
    instructions: [
      'Stand tall, feet hip-width, near a wall for balance if needed.',
      'Rise onto the toes as high as possible, pause.',
      'Lower slowly past level for a full stretch.',
    ],
    videoSearch: 'standing calf raise form tutorial',
  }),
  ex({
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    patterns: ['calfRaise'],
    equipment: ['bodyweight', 'wall'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.65,
    correctiveFit: 0.6,
    jointLoad: ['ankle'],
    progressionOf: 'standing-calf-raise',
    breathCue: 'Exhale rising. Notice which ankle wobbles more — that’s the data.',
    instructions: [
      'Balance on one foot, fingertips on a wall for support only.',
      'Rise onto the toes of the standing leg, pause at the top.',
      'Lower slowly past level, then repeat before switching sides.',
    ],
    videoSearch: 'single leg calf raise form tutorial',
  }),

  /* ---- Abs ladder (home + apartment) ---- */
  ex({
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    patterns: ['coreFlexion'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.55,
    correctiveFit: 0.4,
    jointLoad: ['lowBack'],
    breathCue: 'Exhale as the legs rise. Press the low back into the floor first.',
    instructions: [
      'Lie flat, low back pressed into the floor, legs straight.',
      'Raise the legs to vertical without the low back arching off the floor.',
      'Lower only as far as the low back stays flat, then repeat.',
    ],
    videoSearch: 'lying leg raise form tutorial low back',
  }),
  ex({
    id: 'hanging-knee-raise',
    name: 'Hanging Knee Raise',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['forearms'],
    patterns: ['coreFlexion'],
    equipment: ['pullupBar'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.4,
    jointLoad: ['shoulder'],
    progressionOf: 'lying-leg-raise',
    breathCue: 'Exhale curling the knees up. Resist swinging.',
    instructions: [
      'Hang from the bar, shoulders engaged, not fully relaxed.',
      'Curl the knees up toward the chest without swinging.',
      'Lower under control back to a dead hang.',
    ],
    videoSearch: 'hanging knee raise form tutorial no swing',
    videoUrl: 'https://www.youtube.com/watch?v=p9hhX_Sx5v0',
  }),
  ex({
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['forearms'],
    patterns: ['coreFlexion'],
    equipment: ['pullupBar'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'lowBack'],
    progressionOf: 'hanging-knee-raise',
    breathCue: 'Exhale raising the straight legs. Slow beats high.',
    instructions: [
      'Hang from the bar with legs straight.',
      'Raise the legs to at least parallel without swinging.',
      'Lower slowly under control back to a dead hang.',
    ],
    videoSearch: 'hanging leg raise form tutorial strict',
  }),

  /* ---- Push-up ladder completion ---- */
  ex({
    id: 'feet-elevated-pushup',
    name: 'Feet-Elevated Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bodyweight', 'chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'pushup',
    breathCue: 'Exhale pressing up. Body stays one straight line, hips don’t sag.',
    instructions: [
      'Feet up on a chair or step, hands under the shoulders.',
      'Lower until the chest is a fist off the floor.',
      'Press up without the hips leading or lagging.',
    ],
    videoSearch: 'feet elevated push up form tutorial',
  }),
  ex({
    id: 'deficit-pushup',
    name: 'Deficit Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bodyweight', 'chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'feet-elevated-pushup',
    breathCue: 'Inhale into the deeper stretch, exhale pressing up.',
    instructions: [
      'Hands on two low, stable supports, wider than shoulder width apart.',
      'Lower the chest below hand level for the extra range.',
      'Press back up, keeping the body one straight line.',
    ],
    videoSearch: 'deficit push up form tutorial',
  }),
  ex({
    id: 'archer-pushup',
    name: 'Archer Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: true,
    goalFit: 0.85,
    correctiveFit: 0.5,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'deficit-pushup',
    breathCue: 'Exhale pressing up and away from the bent-arm side.',
    instructions: [
      'Hands well wider than shoulder width.',
      'Shift your weight over one arm, keeping the other arm straight, as you lower.',
      'Press back to center, then repeat shifting to the other side.',
    ],
    videoSearch: 'archer push up form tutorial',
  }),
  ex({
    id: 'one-arm-pushup',
    name: 'One-Arm Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: true,
    goalFit: 0.9,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'archer-pushup',
    breathCue: 'Exhale pressing up. Feet wide for a stable base.',
    instructions: [
      'Feet set wide, one hand behind the back or on the hip.',
      'Lower under total control, resisting any rotation of the torso.',
      'Press back up. The goal, not the starting point.',
    ],
    videoSearch: 'one arm push up progression tutorial',
  }),

  /* ---- Pull-up ladder completion — the actual bug fix ---- */
  ex({
    id: 'pullup',
    name: 'Pull-Up',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['pullupBar'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.95,
    correctiveFit: 0.65,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'negative-pullup',
    breathCue: 'Exhale pulling up, driving the elbows down and back.',
    instructions: [
      'Dead hang start, full range every rep.',
      'Pull until the chin clears the bar without kipping.',
      'Lower all the way back to a dead hang under control.',
    ],
    videoSearch: 'strict pull up form tutorial full range',
  }),
  ex({
    id: 'weighted-pullup',
    name: 'Weighted Pull-Up',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['pullupBar', 'dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 1.0,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'pullup',
    breathCue: 'Exhale pulling up. Brace hard against the extra load.',
    instructions: [
      'Hold a dumbbell between the feet or in a dip belt.',
      'Pull to a full chin-over-bar with strict form.',
      'Lower under complete control — no dropping.',
    ],
    videoSearch: 'weighted pull up form tutorial',
  }),

  /* ---- Dip ---- */
  ex({
    id: 'bench-dip',
    name: 'Bench Dip',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    patterns: ['elbowExtension'],
    equipment: ['bench'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.1,
    jointLoad: ['shoulder', 'elbow', 'wrist'],
    breathCue: 'Inhale lowering, exhale pressing up.',
    instructions: [
      'Hands on the bench edge behind you, legs extended out front.',
      'Lower the hips straight down, elbows tracking back, not out.',
      'Press back up without shrugging the shoulders to the ears.',
    ],
    videoSearch: 'bench dip form tutorial shoulder safe',
  }),

  /* ---- L-sit ladder ---- */
  ex({
    id: 'tuck-hold',
    name: 'Tuck Hold',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders'],
    patterns: ['antiExtension'],
    equipment: ['chair'],
    loadType: 'time',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.5,
    jointLoad: ['hip', 'shoulder', 'wrist'],
    breathCue: 'Breathe shallow and steady — the hold, not the breath, is the challenge.',
    instructions: [
      'Hands on two chairs or blocks at your sides, arms straight.',
      'Lift the hips, knees tucked to the chest, feet off the floor.',
      'Hold with the low back rounded slightly, not arched.',
    ],
    videoSearch: 'tuck hold gymnastics core form',
  }),
  ex({
    id: 'l-sit',
    name: 'L-Sit',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'quads'],
    patterns: ['antiExtension'],
    equipment: ['chair'],
    loadType: 'time',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.5,
    jointLoad: ['hip', 'shoulder', 'wrist'],
    progressionOf: 'tuck-hold',
    breathCue: 'Breathe shallow and steady. Legs straight is the whole game.',
    instructions: [
      'Hands on two chairs or blocks at your sides, arms straight.',
      'Extend both legs straight out in front, parallel to the floor.',
      'Hold as long as the legs stay level and straight.',
    ],
    videoSearch: 'l-sit progression form tutorial',
  }),

  /* ---- Dead hang ---- */
  ex({
    id: 'dead-hang',
    name: 'Dead Hang',
    primaryMuscles: ['lats', 'forearms'],
    secondaryMuscles: ['shoulders'],
    patterns: ['verticalPull'],
    equipment: ['pullupBar'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.6,
    jointLoad: ['shoulder'],
    breathCue: 'Breathe slow and full. Let the shoulder blades relax down and back.',
    instructions: [
      'Grip the bar just past shoulder width, feet off the floor.',
      'Let the shoulders relax down away from the ears — resist shrugging up.',
      'Hold, breathing normally, until grip genuinely fails.',
    ],
    videoSearch: 'dead hang form tutorial grip shoulder health',
  }),

  /* ---- Single-leg squat ladder ---- */
  ex({
    id: 'single-leg-box-squat',
    name: 'Single-Leg Box Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['squat'],
    equipment: ['bodyweight', 'chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: true,
    goalFit: 0.65,
    correctiveFit: 0.9,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'split-squat',
    breathCue: 'Exhale standing. Notice which side needs more help from the hand.',
    instructions: [
      'Stand on one leg in front of a sturdy chair, other leg extended forward.',
      'Sit back to lightly touch the chair, using a hand for balance as needed.',
      'Stand back up through the working leg, taking away hand support as you improve.',
    ],
    videoSearch: 'single leg box squat progression pistol squat',
  }),
  ex({
    id: 'pistol-squat',
    name: 'Pistol Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['squat'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: true,
    goalFit: 0.75,
    correctiveFit: 0.95,
    jointLoad: ['knee', 'hip', 'ankle'],
    progressionOf: 'single-leg-box-squat',
    breathCue: 'Exhale standing. This is a goal, not a warmup — patience.',
    instructions: [
      'Stand on one leg, other leg extended straight out in front.',
      'Lower under full control until the hip is below the knee.',
      'Stand back up through the heel without the other foot touching down.',
    ],
    videoSearch: 'pistol squat progression tutorial',
  }),

  /* ---- Hollow body hold ---- */
  ex({
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['glutes'],
    patterns: ['antiExtension'],
    equipment: ['mat'],
    loadType: 'time',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.55,
    correctiveFit: 0.6,
    jointLoad: ['lowBack'],
    progressionOf: 'plank',
    breathCue: 'Breathe shallow into the chest — a full belly breath breaks the brace.',
    instructions: [
      'Lie on your back, low back pressed flat into the floor.',
      'Raise the shoulders and legs off the floor into a slight curve.',
      'Hold only as long as the low back stays pinned to the floor.',
    ],
    videoSearch: 'hollow body hold form tutorial gymnastics',
  }),
];

export const CATALOG_BY_ID = new Map(CATALOG.map((e) => [e.id, e]));
