/**
 * KEEL exercise catalog — Cruise Block (Block 1).
 *
 * Hand-authored rather than imported, because the metadata that matters here —
 * ladder edges, breath cues, corrective value, joint load — doesn't exist in
 * any public dataset. `catalog/scripts/build-catalog.mjs` pulls the
 * public-domain free-exercise-db to *expand* this library later with imagery
 * and long-tail movements; it can't replace the authored fields.
 *
 * Two things shape every entry:
 *
 *   Entry rungs sit low. At ~290 lb a full push-up and a pull-up are goals,
 *   not warmups. Ladders that start where you actually are turn a demoralising
 *   gap into a countable number of rungs.
 *
 *   Corrective value is a first-class score. Anti-extension, offset carries,
 *   and breath-driven repositioning directly oppose an anterior pelvic tilt,
 *   a right-side shift, and rolled-forward shoulders.
 *
 * NOTE ON VIDEOS: `videoSearch` holds a precise search query rather than a
 * hardcoded video id. Inventing YouTube ids would produce dead or wrong links,
 * which for technique instruction is worse than no link at all. Verified
 * per-exercise embeds are a follow-up pass.
 */

import type { Exercise } from '../src/engine/types';

type Draft = Omit<Exercise, 'images' | 'secondaryMuscles' | 'instructions'> &
  Partial<Pick<Exercise, 'images' | 'secondaryMuscles' | 'instructions'>> & {
    videoSearch?: string;
  };

function ex(d: Draft): Exercise & { videoSearch?: string } {
  return {
    images: [],
    secondaryMuscles: [],
    instructions: [],
    ...d,
  };
}

export const CATALOG: (Exercise & { videoSearch?: string })[] = [
  /* ---------------------------------------------------------------- *
   * BRIDGE — the corrective centrepiece
   *
   * The 90/90 hip lift is where breath work and posture stop being two
   * separate goals. A full exhale drops the ribcage, which lets the pelvis
   * rotate out of anterior tilt; the position is the drill.
   * ---------------------------------------------------------------- */
  ex({
    id: 'hip-lift-90-90',
    name: '90/90 Hip Lift',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['bridge'],
    equipment: ['mat', 'wall'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.2,
    correctiveFit: 1.0,
    jointLoad: [],
    tempo: 'slow',
    breathCue: 'Exhale fully through the mouth. Feel the ribs drop before you lift.',
    instructions: [
      'Lie on your back, feet flat on a wall, hips and knees at 90 degrees.',
      'Exhale fully through pursed lips until your lower back flattens to the floor.',
      'Keeping that flat back, push through your heels to lift your tailbone an inch.',
      'Hold, breathe quietly through your nose for 4 breaths, then lower.',
    ],
    videoSearch: '90/90 hip lift with balloon PRI tutorial',
  }),
  ex({
    id: 'glute-bridge',
    name: 'Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'lowerBack'],
    patterns: ['bridge'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.75,
    jointLoad: ['lowBack'],
    progressionOf: 'hip-lift-90-90',
    breathCue: 'Exhale as you lift. Ribs stay down — do not arch to get higher.',
    instructions: [
      'Lie on your back, knees bent, feet flat and hip-width.',
      'Exhale, tuck the pelvis slightly, then drive through your heels.',
      'Stop when your hips are in line with your knees and shoulders.',
      'Lower under control.',
    ],
    videoSearch: 'glute bridge proper form posterior pelvic tilt',
  }),
  ex({
    id: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['bridge'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.5,
    correctiveFit: 0.9,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'glute-bridge',
    breathCue: 'Exhale up. Keep both hip bones level — do not let one side hike.',
    instructions: [
      'Set up as a glute bridge, then extend one leg straight.',
      'Drive through the planted heel, keeping the pelvis level.',
      'Lower without letting the free-side hip drop.',
    ],
    videoSearch: 'single leg glute bridge form level hips',
  }),
  ex({
    id: 'hip-thrust-db',
    name: 'Dumbbell Hip Thrust',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    patterns: ['bridge'],
    equipment: ['bench', 'dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.5,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Exhale at the top. Chin tucked, ribs down.',
    instructions: [
      'Sit on the floor with your upper back against a bench, dumbbell across the hips.',
      'Exhale, tuck the pelvis, and drive the hips up until the torso is level.',
      'Pause one second at the top, then lower.',
    ],
    videoSearch: 'dumbbell hip thrust form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * ANTI-EXTENSION — the direct opponent of anterior pelvic tilt
   * ---------------------------------------------------------------- */
  ex({
    id: 'dead-bug',
    name: 'Dead Bug',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['antiExtension'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 1.0,
    jointLoad: [],
    breathCue: 'Long exhale as the limbs travel. The low back never leaves the floor.',
    instructions: [
      'Lie on your back, arms straight up, knees over hips at 90 degrees.',
      'Press your low back into the floor and hold it there.',
      'Exhale slowly while lowering one arm and the opposite leg.',
      'Return, and switch sides. Stop the range where the back starts to lift.',
    ],
    videoSearch: 'dead bug exercise form low back flat',
  }),
  ex({
    id: 'dead-bug-band',
    name: 'Banded Dead Bug',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lats', 'lowerBack'],
    patterns: ['antiExtension'],
    equipment: ['mat', 'band'],
    loadType: 'band',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.35,
    correctiveFit: 0.95,
    jointLoad: [],
    progressionOf: 'dead-bug',
    breathCue: 'Pull the band down as you exhale — lats and abs together.',
    instructions: [
      'Anchor a band overhead and hold it with straight arms.',
      'Press the band toward your hips to switch on the lats.',
      'Keeping that tension, lower one leg at a time on a long exhale.',
    ],
    videoSearch: 'banded dead bug lat tension core exercise',
  }),
  ex({
    id: 'plank',
    name: 'Front Plank',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes'],
    patterns: ['antiExtension'],
    equipment: ['mat'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.7,
    jointLoad: ['shoulder', 'lowBack'],
    progressionOf: 'dead-bug-band',
    breathCue: 'Breathe. If you cannot talk, the position is too hard, not too good.',
    instructions: [
      'Forearms under shoulders, feet hip-width.',
      'Tuck the pelvis so the low back is flat, and squeeze the glutes.',
      'Hold only as long as that position survives.',
    ],
    videoSearch: 'front plank form posterior pelvic tilt glutes',
  }),

  /* ---------------------------------------------------------------- *
   * ANTI-ROTATION
   * ---------------------------------------------------------------- */
  ex({
    id: 'pallof-press-band',
    name: 'Pallof Press',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes'],
    patterns: ['antiRotation'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.35,
    correctiveFit: 0.95,
    jointLoad: [],
    breathCue: 'Exhale as you press out. Resist the twist — nothing should rotate.',
    instructions: [
      'Anchor a band at chest height and stand side-on, hands at your sternum.',
      'Step out until the band is taut.',
      'Press your hands straight forward and resist the pull toward the anchor.',
      'Return under control.',
    ],
    videoSearch: 'pallof press anti rotation core form',
  }),
  ex({
    id: 'pallof-press-half-kneeling',
    name: 'Half-Kneeling Pallof Press',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['glutes', 'shoulders'],
    patterns: ['antiRotation'],
    equipment: ['band', 'mat'],
    loadType: 'band',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.4,
    correctiveFit: 1.0,
    jointLoad: [],
    progressionOf: 'pallof-press-band',
    breathCue: 'Exhale, ribs down, back glute switched on. No arching to press.',
    instructions: [
      'Half-kneel side-on to the anchor, down knee under the hip.',
      'Squeeze the down-side glute and tuck the pelvis.',
      'Press out and resist rotation without letting the ribs flare.',
    ],
    videoSearch: 'half kneeling pallof press form ribs down',
  }),

  /* ---------------------------------------------------------------- *
   * ROTATION
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-chop-low-high',
    name: 'Low-to-High Band Chop',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['shoulders', 'glutes', 'upperBack'],
    patterns: ['rotation'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.4,
    correctiveFit: 0.8,
    jointLoad: ['shoulder'],
    breathCue: 'Exhale through the turn. Rotate from the ribcage, not the low back.',
    instructions: [
      'Anchor a band low and stand side-on.',
      'Pull from the low hip diagonally up and across.',
      'Let the back foot pivot; keep the pelvis stacked over the down leg.',
    ],
    videoSearch: 'low to high band chop rotation exercise form',
  }),
  ex({
    id: 'open-book',
    name: 'Open Book Rotation',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['abs'],
    patterns: ['rotation'],
    equipment: ['mat'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.15,
    correctiveFit: 0.9,
    jointLoad: [],
    breathCue: 'Inhale to open, long exhale at end range.',
    instructions: [
      'Lie on your side, knees stacked at 90 degrees, arms straight in front.',
      'Keeping the knees down, sweep the top arm open across your body.',
      'Follow the hand with your eyes and exhale at the end of the range.',
    ],
    videoSearch: 'open book thoracic rotation stretch form',
  }),

  /* ---------------------------------------------------------------- *
   * CARRY — the lateral-shift exercise
   *
   * A suitcase carry is the most direct loaded answer to bearing weight on
   * one side: an offset load forces the opposite lateral core to hold you
   * upright, and it is immediately obvious which side struggles.
   * ---------------------------------------------------------------- */
  ex({
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    primaryMuscles: ['abs', 'forearms'],
    secondaryMuscles: ['upperBack', 'glutes', 'shoulders'],
    patterns: ['carry'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'novice',
    unilateral: true,
    goalFit: 0.7,
    correctiveFit: 1.0,
    jointLoad: ['lowBack', 'shoulder'],
    breathCue: 'Breathe normally. Stay tall — do not lean away from the weight.',
    instructions: [
      'Hold one dumbbell at your side, shoulders level.',
      'Walk slowly, resisting the pull to the loaded side.',
      'Count reps as paces. Match both sides.',
    ],
    videoSearch: 'suitcase carry form anti lateral flexion',
  }),
  ex({
    id: 'farmer-carry',
    name: 'Farmer Carry',
    primaryMuscles: ['forearms', 'upperBack'],
    secondaryMuscles: ['abs', 'shoulders', 'quads'],
    patterns: ['carry'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'lowBack'],
    breathCue: 'Ribs down, chest tall, breathe steady.',
    instructions: [
      'Hold a dumbbell in each hand at your sides.',
      'Stand tall, pull the shoulders back and down, and walk.',
      'Count reps as paces.',
    ],
    videoSearch: 'farmer carry form grip posture',
  }),

  /* ---------------------------------------------------------------- *
   * SQUAT — entry rung is a chair
   * ---------------------------------------------------------------- */
  ex({
    id: 'box-squat',
    name: 'Box Squat (Sit-to-Stand)',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    patterns: ['squat'],
    equipment: ['chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.4,
    correctiveFit: 0.5,
    jointLoad: ['knee', 'hip'],
    breathCue: 'Inhale down, exhale on the way up.',
    instructions: [
      'Stand in front of a chair, feet shoulder-width.',
      'Push the hips back and sit under control — do not drop.',
      'Stand fully, squeezing the glutes at the top.',
    ],
    videoSearch: 'box squat to chair form beginner',
  }),
  ex({
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'adductors'],
    patterns: ['squat'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.5,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'box-squat',
    breathCue: 'Inhale down, exhale up. Ribs stacked over the pelvis.',
    instructions: [
      'Feet shoulder-width, toes slightly out.',
      'Sit down and back, keeping the whole foot on the floor.',
      'Descend to the depth you can hold without the low back rounding.',
    ],
    videoSearch: 'bodyweight squat form tutorial',
  }),
  ex({
    id: 'goblet-squat',
    name: 'Goblet Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upperBack', 'adductors'],
    patterns: ['squat'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.7,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'bodyweight-squat',
    tempo: '3-1-1-0',
    breathCue: 'Big breath at the top, hold it down, exhale on the way up.',
    instructions: [
      'Hold a dumbbell vertically against your chest.',
      'Squat between your knees, elbows tracking inside the thighs.',
      'The front load helps keep the chest up — let it.',
    ],
    videoSearch: 'goblet squat form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * LUNGE — all unilateral, all asymmetry-exposing
   * ---------------------------------------------------------------- */
  ex({
    id: 'split-squat-supported',
    name: 'Supported Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    patterns: ['lunge'],
    equipment: ['chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.5,
    correctiveFit: 0.9,
    jointLoad: ['knee', 'hip'],
    breathCue: 'Exhale up. Back-side glute stays switched on throughout.',
    instructions: [
      'Stagger your stance, one hand on a chair for balance.',
      'Drop the back knee straight down.',
      'Push through the front heel to stand. Keep the pelvis square.',
    ],
    videoSearch: 'supported split squat form beginner',
  }),
  ex({
    id: 'split-squat',
    name: 'Split Squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'adductors', 'abs'],
    patterns: ['lunge'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.6,
    correctiveFit: 0.95,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'split-squat-supported',
    breathCue: 'Exhale up. Notice which side wobbles — that is the information.',
    instructions: [
      'Stagger your stance without support.',
      'Lower the back knee straight down under control.',
      'Drive through the front heel, keeping the torso upright.',
    ],
    videoSearch: 'split squat form tutorial',
  }),
  ex({
    id: 'reverse-lunge-db',
    name: 'Dumbbell Reverse Lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'adductors'],
    patterns: ['lunge'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'low',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.8,
    correctiveFit: 0.85,
    jointLoad: ['knee', 'hip'],
    progressionOf: 'split-squat',
    breathCue: 'Exhale as you stand. Stay tall through the step back.',
    instructions: [
      'Hold dumbbells at your sides.',
      'Step back and lower the trailing knee toward the floor.',
      'Push through the front heel to return.',
    ],
    videoSearch: 'dumbbell reverse lunge form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * HINGE
   * ---------------------------------------------------------------- */
  ex({
    id: 'hip-hinge-dowel',
    name: 'Hip Hinge Pattern',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack'],
    patterns: ['hinge'],
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.8,
    jointLoad: ['lowBack', 'hip'],
    breathCue: 'Inhale as you hinge back, exhale as you stand.',
    instructions: [
      'Hold a broomstick along your spine, touching head, mid-back, and tailbone.',
      'Push the hips straight back, letting the knees soften.',
      'Keep all three contact points as you hinge, then stand.',
    ],
    videoSearch: 'hip hinge dowel drill three points of contact',
  }),
  ex({
    id: 'rdl-db',
    name: 'Dumbbell Romanian Deadlift',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack', 'upperBack', 'forearms'],
    patterns: ['hinge'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.9,
    correctiveFit: 0.7,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'hip-hinge-dowel',
    tempo: '3-0-1-0',
    breathCue: 'Breath in at the top, hold on the way down, exhale standing up.',
    instructions: [
      'Hold dumbbells in front of your thighs, knees softly bent.',
      'Push the hips back, letting the weights track down your legs.',
      'Stop when the hamstrings tighten or the back starts to round.',
      'Drive the hips forward to stand.',
    ],
    videoSearch: 'dumbbell romanian deadlift form tutorial',
  }),
  ex({
    id: 'single-leg-rdl-supported',
    name: 'Supported Single-Leg RDL',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lowerBack', 'abs'],
    patterns: ['hinge'],
    equipment: ['dumbbell', 'chair'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.7,
    correctiveFit: 1.0,
    jointLoad: ['lowBack', 'hip'],
    progressionOf: 'rdl-db',
    breathCue: 'Exhale standing up. Keep both hip bones pointing at the floor.',
    instructions: [
      'Hold a chair with one hand, dumbbell in the other.',
      'Hinge over the standing leg, letting the free leg travel behind you.',
      'Do not let the free-side hip rotate open.',
    ],
    videoSearch: 'single leg romanian deadlift form hips square',
  }),

  /* ---------------------------------------------------------------- *
   * HORIZONTAL PUSH — the ladder starts at a wall
   * ---------------------------------------------------------------- */
  ex({
    id: 'wall-pushup',
    name: 'Wall Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['wall'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    breathCue: 'Inhale in, exhale pressing away.',
    instructions: [
      'Hands on a wall at chest height, step your feet back.',
      'Lower your chest to the wall with the body in one line.',
      'Press away, spreading the shoulder blades at the top.',
    ],
    videoSearch: 'wall push up proper form beginner',
  }),
  ex({
    id: 'incline-pushup',
    name: 'Incline Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['bench'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.45,
    correctiveFit: 0.45,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'wall-pushup',
    breathCue: 'Exhale pressing up. Ribs down — no sagging through the middle.',
    instructions: [
      'Hands on a bench, body in a straight line from head to heels.',
      'Lower the chest to the bench with elbows at about 45 degrees.',
      'Press up and spread the shoulder blades.',
    ],
    videoSearch: 'incline push up form tutorial',
  }),
  ex({
    id: 'knee-pushup',
    name: 'Knee Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.45,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'incline-pushup',
    breathCue: 'Exhale pressing up. Squeeze the glutes to stop the hips sagging.',
    instructions: [
      'Knees on a mat, hands under the shoulders.',
      'Keep a straight line from knees to head.',
      'Lower the chest, then press up.',
    ],
    videoSearch: 'knee push up correct form',
  }),
  ex({
    id: 'pushup',
    name: 'Push-Up',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'abs'],
    patterns: ['horizontalPush'],
    equipment: ['mat'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.5,
    jointLoad: ['shoulder', 'wrist', 'elbow'],
    progressionOf: 'knee-pushup',
    breathCue: 'Exhale pressing up. Whole body moves as one plank.',
    instructions: [
      'Hands under the shoulders, feet hip-width, body in one line.',
      'Lower until the chest is a fist off the floor.',
      'Press up without letting the hips lead or lag.',
    ],
    videoSearch: 'push up perfect form tutorial',
  }),
  ex({
    id: 'floor-press-db',
    name: 'Dumbbell Floor Press',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    patterns: ['horizontalPush'],
    equipment: ['dumbbell', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.4,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Inhale down, exhale press. Low back stays flat on the floor.',
    instructions: [
      'Lie on your back on a mat, knees bent, dumbbells at chest height.',
      'Press up until the arms are straight.',
      'Lower until the triceps touch the floor, pause, repeat.',
    ],
    videoSearch: 'dumbbell floor press form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * VERTICAL PUSH
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-overhead-press',
    name: 'Band Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upperBack', 'abs'],
    patterns: ['verticalPush'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.5,
    correctiveFit: 0.6,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing up. Ribs down — press with the shoulder, not the back.',
    instructions: [
      'Stand on a band, handles at shoulder height.',
      'Press straight overhead without leaning back.',
      'Lower under control.',
    ],
    videoSearch: 'band overhead press form ribs down',
  }),
  ex({
    id: 'overhead-press-db-seated',
    name: 'Seated Dumbbell Overhead Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'upperBack'],
    patterns: ['verticalPush'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.5,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing up. Back stays flat against the bench.',
    instructions: [
      'Sit upright with back support, dumbbells at shoulder height.',
      'Press overhead until the arms are straight.',
      'Lower to ear height under control.',
    ],
    videoSearch: 'seated dumbbell shoulder press form',
  }),
  ex({
    id: 'half-kneeling-press-db',
    name: 'Half-Kneeling Single-Arm Press',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['abs', 'triceps', 'glutes'],
    patterns: ['verticalPush'],
    equipment: ['dumbbell', 'mat'],
    loadType: 'external',
    impact: 'none',
    level: 'intermediate',
    unilateral: true,
    goalFit: 0.75,
    correctiveFit: 0.95,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pressing. Back glute on, ribs down, no arching.',
    instructions: [
      'Half-kneel with the down knee under the hip, dumbbell in the opposite hand.',
      'Squeeze the down-side glute and tuck the pelvis.',
      'Press overhead without letting the ribs flare or the torso lean.',
    ],
    videoSearch: 'half kneeling single arm dumbbell press form',
  }),

  /* ---------------------------------------------------------------- *
   * HORIZONTAL PULL — the highest-value pattern here
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-row',
    name: 'Seated Band Row',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['lats', 'biceps', 'forearms'],
    patterns: ['horizontalPull'],
    equipment: ['band'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.9,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Lead with the shoulder blades, not the hands.',
    instructions: [
      'Sit with legs extended, band around the feet.',
      'Pull the handles to your ribs, squeezing the shoulder blades together.',
      'Return slowly, letting the blades travel forward.',
    ],
    videoSearch: 'seated band row form scapular retraction',
  }),
  ex({
    id: 'bent-row-db',
    name: 'Dumbbell Bent-Over Row',
    primaryMuscles: ['upperBack', 'lats'],
    secondaryMuscles: ['biceps', 'forearms', 'lowerBack'],
    patterns: ['horizontalPull'],
    equipment: ['dumbbell'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.95,
    correctiveFit: 0.85,
    jointLoad: ['lowBack', 'shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Chest stays proud, low back neutral.',
    instructions: [
      'Hinge to about 45 degrees, dumbbells hanging.',
      'Row to the ribs, driving the elbows back and squeezing the blades.',
      'Lower under control.',
    ],
    videoSearch: 'dumbbell bent over row form tutorial',
  }),
  ex({
    id: 'single-arm-row-db',
    name: 'Single-Arm Dumbbell Row',
    primaryMuscles: ['lats', 'upperBack'],
    secondaryMuscles: ['biceps', 'forearms', 'abs'],
    patterns: ['horizontalPull'],
    equipment: ['dumbbell', 'bench'],
    loadType: 'external',
    impact: 'none',
    level: 'novice',
    unilateral: true,
    goalFit: 0.9,
    correctiveFit: 1.0,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling. Do not let the torso rotate to help.',
    instructions: [
      'One hand and knee on a bench, other foot planted.',
      'Row the dumbbell to your hip, elbow close.',
      'Lower fully and let the shoulder blade reach forward at the bottom.',
    ],
    videoSearch: 'single arm dumbbell row form no rotation',
  }),
  ex({
    id: 'suspension-row',
    name: 'Suspension Row',
    primaryMuscles: ['upperBack'],
    secondaryMuscles: ['lats', 'biceps', 'abs'],
    patterns: ['horizontalPull'],
    equipment: ['suspension'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.8,
    correctiveFit: 0.95,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'band-row',
    breathCue: 'Exhale pulling. Body stays one straight line, ribs down.',
    instructions: [
      'Hold the straps and walk your feet forward to set the angle.',
      'Pull your chest to your hands, squeezing the shoulder blades.',
      'The more upright you stand, the easier it is — use that to scale.',
    ],
    videoSearch: 'TRX suspension row form tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * VERTICAL PULL — a pull-up is a goal, not a starting point
   * ---------------------------------------------------------------- */
  ex({
    id: 'band-lat-pulldown',
    name: 'Band Lat Pulldown',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps'],
    patterns: ['verticalPull'],
    equipment: ['band', 'pullupBar'],
    loadType: 'band',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.6,
    correctiveFit: 0.8,
    jointLoad: ['shoulder', 'elbow'],
    breathCue: 'Exhale pulling down. Start the pull from the armpit.',
    instructions: [
      'Anchor a band over the pull-up bar and kneel underneath.',
      'Pull the band down to your chest, elbows driving to the ribs.',
      'Return slowly and let the shoulder blades rise at the top.',
    ],
    videoSearch: 'band lat pulldown kneeling form',
  }),
  ex({
    id: 'suspension-assisted-pullup',
    name: 'Suspension-Assisted Pull-Up',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['suspension'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'intermediate',
    unilateral: false,
    goalFit: 0.75,
    correctiveFit: 0.75,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'band-lat-pulldown',
    breathCue: 'Exhale pulling up. Let the legs help exactly as much as needed.',
    instructions: [
      'Set the straps so the handles are at chest height, feet in front.',
      'Pull yourself up, driving the elbows down and back.',
      'Use the legs to assist, taking away help as you get stronger.',
    ],
    videoSearch: 'TRX assisted pull up progression',
  }),
  ex({
    id: 'negative-pullup',
    name: 'Pull-Up Negative',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upperBack', 'biceps', 'forearms'],
    patterns: ['verticalPull'],
    equipment: ['pullupBar', 'chair'],
    loadType: 'bodyweight',
    impact: 'none',
    level: 'advanced',
    unilateral: false,
    goalFit: 0.85,
    correctiveFit: 0.7,
    jointLoad: ['shoulder', 'elbow'],
    progressionOf: 'suspension-assisted-pullup',
    tempo: '5-0-0-0',
    breathCue: 'Breathe steadily through the descent. Control beats speed.',
    instructions: [
      'Step up so your chin starts above the bar.',
      'Lower yourself as slowly as you can — aim for five seconds.',
      'Step back up to reset. Never drop off the bar.',
    ],
    videoSearch: 'pull up negatives progression tutorial',
  }),

  /* ---------------------------------------------------------------- *
   * NECK — wrestler build and forward-head posture, same work
   * ---------------------------------------------------------------- */
  ex({
    id: 'neck-isometric',
    name: 'Neck Isometrics',
    primaryMuscles: ['neck'],
    secondaryMuscles: [],
    patterns: ['neck'],
    equipment: ['bodyweight'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.7,
    correctiveFit: 0.8,
    jointLoad: ['neck'],
    breathCue: 'Breathe normally throughout. Never hold your breath here.',
    instructions: [
      'Place a palm on your forehead and press your head into it gently.',
      'Build to about half effort over three seconds and hold.',
      'Repeat on the back and each side. Nothing should move.',
    ],
    videoSearch: 'neck isometric exercise safe form',
  }),
  ex({
    id: 'chin-tuck',
    name: 'Chin Tuck',
    primaryMuscles: ['neck'],
    secondaryMuscles: ['upperBack'],
    patterns: ['neck'],
    equipment: ['bodyweight'],
    loadType: 'time',
    impact: 'none',
    level: 'novice',
    unilateral: false,
    goalFit: 0.3,
    correctiveFit: 1.0,
    jointLoad: ['neck'],
    breathCue: 'Exhale as you tuck. Slow and small.',
    instructions: [
      'Sit or stand tall, eyes level.',
      'Draw the chin straight back, making a double chin.',
      'Hold three seconds and release. Small range, no tilting.',
    ],
    videoSearch: 'chin tuck exercise forward head posture',
  }),
];

export const CATALOG_BY_ID = new Map(CATALOG.map((e) => [e.id, e]));
